import { HandlersSubscriptionResponse } from "@/app/api/generated/schemas";

export const subscriptions: HandlersSubscriptionResponse[] = [
    {
        amount: 1200,
        billingCycle: "月",
        currency: "JPY",
        customData: [1, 2, 3],
        email: "test@example.com",
        encPassword: [1, 2, 3],
        iconUrl: "/icons/google.png",
        id: 1,
        isDisclosed: true,
        memo: "メモ",
        message: "メッセージ",
        passerID: "user1",
        plsDelete: false,
        serviceName: "Netflix",
        trustID: 1,
        username: "user1",
    },
    {
        amount: 990,
        billingCycle: "月",
        currency: "JPY",
        customData: [4, 5, 6],
        email: "test@example.com",
        encPassword: [4, 5, 6],
        iconUrl: "/icons/twitter.png",
        id: 2,
        isDisclosed: true,
        memo: "メモ",
        message: "メッセージ",
        passerID: "user2",
        plsDelete: false,
        serviceName: "Spotfy",
        trustID: 2,
        username: "user2",
    },
    {
        amount: 1280,
        billingCycle: "月",
        currency: "JPY",
        customData: [7, 8, 9],
        email: "test@example.com",
        encPassword: [7, 8, 9],
        iconUrl: "/icons/facebook.png",
        id: 3,
        isDisclosed: true,
        memo: "メモ",
        message: "メッセージ",
        passerID: "user3",
        plsDelete: false,
        serviceName: "Youtube Premium",
        trustID: 3,
        username: "user3",
    },
    {
        amount: 3000,
        billingCycle: "月",
        currency: "JPY",
        customData: [10, 11, 12],
        email: "test@example.com",
        encPassword: [10, 11, 12],
        iconUrl: "/icons/linkedin.png",
        id: 4,
        isDisclosed: true,
        memo: "メモ",
        message: "メッセージ",
        passerID: "user4",
        plsDelete: false,
        serviceName: "ChatGPT Pro",
        trustID: 4,
        username: "user4",
    },
    {
        amount: 980,
        billingCycle: "月",
        currency: "JPY",
        customData: [13, 14, 15],
        email: "test@example.com",
        encPassword: [13, 14, 15],
        iconUrl: "/icons/github.png",
        id: 5,
        isDisclosed: true,
        memo: "メモ",
        message: "メッセージ",
        passerID: "user5",
        plsDelete: false,
        serviceName: "GitHub Pro",
        trustID: 5,
        username: "user5",
    },
];
