// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: passkeys.mut.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const savePasskey = `-- name: SavePasskey :one
INSERT INTO passkeys (user_id,
                      rp_id,
                      private_key)
VALUES ($1, -- user_id
        $2, -- rp_id
        $3 -- private_key
       )
RETURNING id, user_id, rp_id, private_key
`

type SavePasskeyParams struct {
	UserID     pgtype.UUID
	RpID       string
	PrivateKey []byte
}

func (q *Queries) SavePasskey(ctx context.Context, arg SavePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, savePasskey, arg.UserID, arg.RpID, arg.PrivateKey)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RpID,
		&i.PrivateKey,
	)
	return i, err
}
