// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: passkeys.query.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPasskeyByUserAndRp = `-- name: GetPasskeyByUserAndRp :one
SELECT id,
       user_id,
       rp_id,
       private_key
FROM passkeys
WHERE user_id = $1
  AND rp_id = $2
`

type GetPasskeyByUserAndRpParams struct {
	UserID pgtype.UUID
	RpID   string
}

func (q *Queries) GetPasskeyByUserAndRp(ctx context.Context, arg GetPasskeyByUserAndRpParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, getPasskeyByUserAndRp, arg.UserID, arg.RpID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RpID,
		&i.PrivateKey,
	)
	return i, err
}
