// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rls.sql

package query

import (
	"context"
)

const assumeUserID = `-- name: AssumeUserID :exec
SET LOCAL digi_baton.current_user_id = $1
`

func (q *Queries) AssumeUserID(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, assumeUserID, dollar_1)
	return err
}
