name: "[Crypto] Deploy to Azure Container Registry"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azure-deploy-crypto.yml'
      - 'crypto/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/azure-deploy-crypto.yml'
concurrency:
  group: deploy-crypto
  cancel-in-progress: true
jobs:
  build_and_push:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: crypto/go.mod
          cache-dependency-path: crypto/go.sum
      - name: Execute Build
        run: |
          go build -o ./crypto/main ./crypto
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Enable Docker buildx
      - name: Azure Login (OIDC)
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          # Replace with your actual registry name in lowercase
          login-server: digibaton.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        # Log in to ACR
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./crypto
          file: ./crypto/build/Dockerfile.prod
          tags: digibaton.azurecr.io/crypto-dev:latest
          push: true
      - name: Create a new revison for containerapp
        run: |
           az containerapp update \
              --resource-group digi-baton \
              --name backend-dev \
              --container-name crypto-dev \
              --image "digibaton.azurecr.io/crypto-dev:latest" \
              --revision-suffix "manual-$(date +%s)"
