name: Deploy to Azure Container Registry - Backend
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azure-deploy-backend.yml'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/azure-deploy-backend.yml'
concurrency:
  group: deploy-backend
  cancel-in-progress: true
jobs:
  build_and_push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Pull the repository code
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Enable Docker buildx
      - name: Azure Login (OIDC)
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          # Replace with your actual registry name in lowercase
          login-server: digibatonbackenddev.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        # Log in to ACR
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: digibatonbackenddev.azurecr.io/backend:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Build and push Docker image
