name: "[Chrome] Lint Check"
on:
  push:
    branches: [ main, dev ]
  pull_request:
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: cd chrome-ext && pnpm install
      - run: cd chrome-ext && pnpm prettier
