name: "[Chrome] Build And Upload Extension Zip Via Artifact"
on:
  push:
    branches: [ main, dev ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: cd chrome-ext && pnpm install --frozen-lockfile --prefer-offline
      - run: cd chrome-ext && pnpm build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
